### ISSUE TITLE
Update document for Props

### ISSUE THREAD

**Issue by devswift2017** [githuboftigran/rn-range-slider#23]
Hi pro. If you have free time you can update name props for component.
Current iOS and android react method difference.
![image](https://user-images.githubusercontent.com/27657751/63535202-1ce4a680-c53b-11e9-8064-a4364d01e570.png)

**Comment by githuboftigran** [comment]
@devswift2017 , I didn't really get.
RangeSlider component has props: `onTouchStart` and `onTouchEnd`. These callbacks are passed to native views with names `onSliderTouchStart` and `onSliderTouchEnd` correspondingly (couldn't use `onTouchStart`, because iOS already has a method with that name and it was causing some problems).
And in iOS and Android views I get those callbacks by name.
So didn't really understand what's the problem.

**Comment by devswift2017** [comment]
Huh, when I apply again then work perfect :) Sorry I'll close issue.
