### ISSUE TITLE
Non-hidden labels and fontFamily for label text

### ISSUE THREAD

**Issue by tomthornton** [githuboftigran/rn-range-slider#34]
Needs the option to always show the label and have ability to change the font for the label

**Comment by githuboftigran** [comment]
@tomthornton  , thanks for the question.
It's not possible to always show labels and I don't actually want to add this functionality because I think this won't be good in terms of UI/UX.
A similar [issue #15](https://github.com/githuboftigran/rn-range-slider/issues/15) was created a long ago. I explained my position there, please read.

Custom fonts are not supported yet. I may add support in future, but not now.
