### ISSUE TITLE
Label for each points

### ISSUE THREAD

**Issue by ilya-raevskiy** [githuboftigran/rn-range-slider#35]
Is it possible to do so

<img width="303" alt="Снимок экрана 2019-12-13 в 23 03 12" src="https://user-images.githubusercontent.com/1379392/70821448-e9d16600-1dfc-11ea-9890-6d45b6cdac45.png">

**Comment by githuboftigran** [comment]
@ilya-raevskiy , thanks for the question.
It's not possible and I don't actually want to add this functionality because I think this won't be good in terms of UI/UX.
A similar [issue #15](https://github.com/githuboftigran/rn-range-slider/issues/15) was created a long ago. I explained my position there, please read.

**Comment by kuldeepGomilestone** [comment]
Hey @ilya-raevskiy , i know it's a bit late but i managed to make both the labels permanent , i modified the below mentioned file.
