### ISSUE TITLE
How to add distance in min and max values?

### ISSUE THREAD

**Issue by kamlesh71** [githuboftigran/rn-range-slider#55]
I want to allow users to select the age range with minimum of 5 years.

**Comment by shareef-dweikat** [comment]
Can you elaborate? I don't get what you need exactly.

**Comment by githuboftigran** [comment]
As I understand, @kamlesh71 wants to allow to select a range "wider" than a predefined value.
For example not allow ranges smaller than 3. [4, 9], [7, 11], [1, 5] are allowed, but [2, 3] is not allowed, because range size for first 3 are: 5, 4, 4 and range size of the last one is 1.
@kamlesh71 , am I right?

**Comment by kamlesh71** [comment]
@shareef-dweikat in case of the price range, I want to allow the user to select min and max price but the gap between min and max price should at least 500. Currently, users can select the same value for min and max price at the same time.

**Comment by githuboftigran** [comment]
@kamlesh71 , I'll work on this in near future.

**Comment by githuboftigran** [comment]
@kamlesh71 , finally added support in version 2.1.0:
https://www.npmjs.com/package/rn-range-slider/v/2.1.0

However this prevents only user from selecting smaller range. It's possible to programmatically set any values.
